// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHunting.antiqueService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AntiqueServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AntiqueService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NLParserOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateRequestXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateRequestXmlUriOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateXmlUriOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveRequestXmlSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveRequestXmlSampleOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveResponseXmlSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveResponseDetailedXmlSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateSimilarityOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConvertToNewDomainOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateCreativityPromptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateCreativityCluesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePredicatesFromDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneratePredicatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveAllSourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformAntiqueOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformAntiqueSampleOperationCompleted;
        
        /// CodeRemarks
        public AntiqueService() {
            this.Url = "http://achernar.soi.city.ac.uk/ESD/ClassLibraries/Antique/Antique.AntiqueService/AntiqueService.asmx";
        }
        
        public AntiqueService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event NLParserCompletedEventHandler NLParserCompleted;
        
        /// CodeRemarks
        public event ValidateRequestXmlCompletedEventHandler ValidateRequestXmlCompleted;
        
        /// CodeRemarks
        public event ValidateRequestXmlUriCompletedEventHandler ValidateRequestXmlUriCompleted;
        
        /// CodeRemarks
        public event ValidateXmlCompletedEventHandler ValidateXmlCompleted;
        
        /// CodeRemarks
        public event ValidateXmlUriCompletedEventHandler ValidateXmlUriCompleted;
        
        /// CodeRemarks
        public event RetrieveRequestXmlSchemaCompletedEventHandler RetrieveRequestXmlSchemaCompleted;
        
        /// CodeRemarks
        public event RetrieveRequestXmlSampleCompletedEventHandler RetrieveRequestXmlSampleCompleted;
        
        /// CodeRemarks
        public event RetrieveResponseXmlSchemaCompletedEventHandler RetrieveResponseXmlSchemaCompleted;
        
        /// CodeRemarks
        public event RetrieveResponseDetailedXmlSchemaCompletedEventHandler RetrieveResponseDetailedXmlSchemaCompleted;
        
        /// CodeRemarks
        public event CalculateSimilarityCompletedEventHandler CalculateSimilarityCompleted;
        
        /// CodeRemarks
        public event ConvertToNewDomainCompletedEventHandler ConvertToNewDomainCompleted;
        
        /// CodeRemarks
        public event GenerateCreativityPromptsCompletedEventHandler GenerateCreativityPromptsCompleted;
        
        /// CodeRemarks
        public event GenerateCreativityCluesCompletedEventHandler GenerateCreativityCluesCompleted;
        
        /// CodeRemarks
        public event GeneratePredicatesFromDocumentCompletedEventHandler GeneratePredicatesFromDocumentCompleted;
        
        /// CodeRemarks
        public event GeneratePredicatesCompletedEventHandler GeneratePredicatesCompleted;
        
        /// CodeRemarks
        public event RetrieveAllSourcesCompletedEventHandler RetrieveAllSourcesCompleted;
        
        /// CodeRemarks
        public event PerformAntiqueCompletedEventHandler PerformAntiqueCompleted;
        
        /// CodeRemarks
        public event PerformAntiqueSampleCompletedEventHandler PerformAntiqueSampleCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NLParser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NLParser(string toCreate) {
            object[] results = this.Invoke("NLParser", new object[] {
                        toCreate});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void NLParserAsync(string toCreate) {
            this.NLParserAsync(toCreate, null);
        }
        
        /// CodeRemarks
        public void NLParserAsync(string toCreate, object userState) {
            if ((this.NLParserOperationCompleted == null)) {
                this.NLParserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNLParserOperationCompleted);
            }
            this.InvokeAsync("NLParser", new object[] {
                        toCreate}, this.NLParserOperationCompleted, userState);
        }
        
        private void OnNLParserOperationCompleted(object arg) {
            if ((this.NLParserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NLParserCompleted(this, new NLParserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateRequestXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateRequestXml(string xml) {
            object[] results = this.Invoke("ValidateRequestXml", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void ValidateRequestXmlAsync(string xml) {
            this.ValidateRequestXmlAsync(xml, null);
        }
        
        /// CodeRemarks
        public void ValidateRequestXmlAsync(string xml, object userState) {
            if ((this.ValidateRequestXmlOperationCompleted == null)) {
                this.ValidateRequestXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateRequestXmlOperationCompleted);
            }
            this.InvokeAsync("ValidateRequestXml", new object[] {
                        xml}, this.ValidateRequestXmlOperationCompleted, userState);
        }
        
        private void OnValidateRequestXmlOperationCompleted(object arg) {
            if ((this.ValidateRequestXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateRequestXmlCompleted(this, new ValidateRequestXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateRequestXmlUri", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateRequestXmlUri(string xmlUri) {
            object[] results = this.Invoke("ValidateRequestXmlUri", new object[] {
                        xmlUri});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void ValidateRequestXmlUriAsync(string xmlUri) {
            this.ValidateRequestXmlUriAsync(xmlUri, null);
        }
        
        /// CodeRemarks
        public void ValidateRequestXmlUriAsync(string xmlUri, object userState) {
            if ((this.ValidateRequestXmlUriOperationCompleted == null)) {
                this.ValidateRequestXmlUriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateRequestXmlUriOperationCompleted);
            }
            this.InvokeAsync("ValidateRequestXmlUri", new object[] {
                        xmlUri}, this.ValidateRequestXmlUriOperationCompleted, userState);
        }
        
        private void OnValidateRequestXmlUriOperationCompleted(object arg) {
            if ((this.ValidateRequestXmlUriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateRequestXmlUriCompleted(this, new ValidateRequestXmlUriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateXml(string xml, string schemaNamespace, string schemaUri) {
            object[] results = this.Invoke("ValidateXml", new object[] {
                        xml,
                        schemaNamespace,
                        schemaUri});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void ValidateXmlAsync(string xml, string schemaNamespace, string schemaUri) {
            this.ValidateXmlAsync(xml, schemaNamespace, schemaUri, null);
        }
        
        /// CodeRemarks
        public void ValidateXmlAsync(string xml, string schemaNamespace, string schemaUri, object userState) {
            if ((this.ValidateXmlOperationCompleted == null)) {
                this.ValidateXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateXmlOperationCompleted);
            }
            this.InvokeAsync("ValidateXml", new object[] {
                        xml,
                        schemaNamespace,
                        schemaUri}, this.ValidateXmlOperationCompleted, userState);
        }
        
        private void OnValidateXmlOperationCompleted(object arg) {
            if ((this.ValidateXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateXmlCompleted(this, new ValidateXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateXmlUri", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateXmlUri(string xmlUri, string schemaNamespace, string schemaUri) {
            object[] results = this.Invoke("ValidateXmlUri", new object[] {
                        xmlUri,
                        schemaNamespace,
                        schemaUri});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void ValidateXmlUriAsync(string xmlUri, string schemaNamespace, string schemaUri) {
            this.ValidateXmlUriAsync(xmlUri, schemaNamespace, schemaUri, null);
        }
        
        /// CodeRemarks
        public void ValidateXmlUriAsync(string xmlUri, string schemaNamespace, string schemaUri, object userState) {
            if ((this.ValidateXmlUriOperationCompleted == null)) {
                this.ValidateXmlUriOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateXmlUriOperationCompleted);
            }
            this.InvokeAsync("ValidateXmlUri", new object[] {
                        xmlUri,
                        schemaNamespace,
                        schemaUri}, this.ValidateXmlUriOperationCompleted, userState);
        }
        
        private void OnValidateXmlUriOperationCompleted(object arg) {
            if ((this.ValidateXmlUriCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateXmlUriCompleted(this, new ValidateXmlUriCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveRequestXmlSchema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveRequestXmlSchema() {
            object[] results = this.Invoke("RetrieveRequestXmlSchema", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveRequestXmlSchemaAsync() {
            this.RetrieveRequestXmlSchemaAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveRequestXmlSchemaAsync(object userState) {
            if ((this.RetrieveRequestXmlSchemaOperationCompleted == null)) {
                this.RetrieveRequestXmlSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveRequestXmlSchemaOperationCompleted);
            }
            this.InvokeAsync("RetrieveRequestXmlSchema", new object[0], this.RetrieveRequestXmlSchemaOperationCompleted, userState);
        }
        
        private void OnRetrieveRequestXmlSchemaOperationCompleted(object arg) {
            if ((this.RetrieveRequestXmlSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveRequestXmlSchemaCompleted(this, new RetrieveRequestXmlSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveRequestXmlSample", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveRequestXmlSample() {
            object[] results = this.Invoke("RetrieveRequestXmlSample", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveRequestXmlSampleAsync() {
            this.RetrieveRequestXmlSampleAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveRequestXmlSampleAsync(object userState) {
            if ((this.RetrieveRequestXmlSampleOperationCompleted == null)) {
                this.RetrieveRequestXmlSampleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveRequestXmlSampleOperationCompleted);
            }
            this.InvokeAsync("RetrieveRequestXmlSample", new object[0], this.RetrieveRequestXmlSampleOperationCompleted, userState);
        }
        
        private void OnRetrieveRequestXmlSampleOperationCompleted(object arg) {
            if ((this.RetrieveRequestXmlSampleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveRequestXmlSampleCompleted(this, new RetrieveRequestXmlSampleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveResponseXmlSchema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveResponseXmlSchema() {
            object[] results = this.Invoke("RetrieveResponseXmlSchema", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveResponseXmlSchemaAsync() {
            this.RetrieveResponseXmlSchemaAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveResponseXmlSchemaAsync(object userState) {
            if ((this.RetrieveResponseXmlSchemaOperationCompleted == null)) {
                this.RetrieveResponseXmlSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveResponseXmlSchemaOperationCompleted);
            }
            this.InvokeAsync("RetrieveResponseXmlSchema", new object[0], this.RetrieveResponseXmlSchemaOperationCompleted, userState);
        }
        
        private void OnRetrieveResponseXmlSchemaOperationCompleted(object arg) {
            if ((this.RetrieveResponseXmlSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveResponseXmlSchemaCompleted(this, new RetrieveResponseXmlSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveResponseDetailedXmlSchema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveResponseDetailedXmlSchema() {
            object[] results = this.Invoke("RetrieveResponseDetailedXmlSchema", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveResponseDetailedXmlSchemaAsync() {
            this.RetrieveResponseDetailedXmlSchemaAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveResponseDetailedXmlSchemaAsync(object userState) {
            if ((this.RetrieveResponseDetailedXmlSchemaOperationCompleted == null)) {
                this.RetrieveResponseDetailedXmlSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveResponseDetailedXmlSchemaOperationCompleted);
            }
            this.InvokeAsync("RetrieveResponseDetailedXmlSchema", new object[0], this.RetrieveResponseDetailedXmlSchemaOperationCompleted, userState);
        }
        
        private void OnRetrieveResponseDetailedXmlSchemaOperationCompleted(object arg) {
            if ((this.RetrieveResponseDetailedXmlSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveResponseDetailedXmlSchemaCompleted(this, new RetrieveResponseDetailedXmlSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CalculateSimilarity", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CalculateSimilarity(string text1, string text2) {
            object[] results = this.Invoke("CalculateSimilarity", new object[] {
                        text1,
                        text2});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void CalculateSimilarityAsync(string text1, string text2) {
            this.CalculateSimilarityAsync(text1, text2, null);
        }
        
        /// CodeRemarks
        public void CalculateSimilarityAsync(string text1, string text2, object userState) {
            if ((this.CalculateSimilarityOperationCompleted == null)) {
                this.CalculateSimilarityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateSimilarityOperationCompleted);
            }
            this.InvokeAsync("CalculateSimilarity", new object[] {
                        text1,
                        text2}, this.CalculateSimilarityOperationCompleted, userState);
        }
        
        private void OnCalculateSimilarityOperationCompleted(object arg) {
            if ((this.CalculateSimilarityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateSimilarityCompleted(this, new CalculateSimilarityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConvertToNewDomain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConvertToNewDomain(string text, string targetDomain, string sourceDomain) {
            object[] results = this.Invoke("ConvertToNewDomain", new object[] {
                        text,
                        targetDomain,
                        sourceDomain});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void ConvertToNewDomainAsync(string text, string targetDomain, string sourceDomain) {
            this.ConvertToNewDomainAsync(text, targetDomain, sourceDomain, null);
        }
        
        /// CodeRemarks
        public void ConvertToNewDomainAsync(string text, string targetDomain, string sourceDomain, object userState) {
            if ((this.ConvertToNewDomainOperationCompleted == null)) {
                this.ConvertToNewDomainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConvertToNewDomainOperationCompleted);
            }
            this.InvokeAsync("ConvertToNewDomain", new object[] {
                        text,
                        targetDomain,
                        sourceDomain}, this.ConvertToNewDomainOperationCompleted, userState);
        }
        
        private void OnConvertToNewDomainOperationCompleted(object arg) {
            if ((this.ConvertToNewDomainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConvertToNewDomainCompleted(this, new ConvertToNewDomainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateCreativityPrompts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateCreativityPrompts(string text) {
            object[] results = this.Invoke("GenerateCreativityPrompts", new object[] {
                        text});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void GenerateCreativityPromptsAsync(string text) {
            this.GenerateCreativityPromptsAsync(text, null);
        }
        
        /// CodeRemarks
        public void GenerateCreativityPromptsAsync(string text, object userState) {
            if ((this.GenerateCreativityPromptsOperationCompleted == null)) {
                this.GenerateCreativityPromptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateCreativityPromptsOperationCompleted);
            }
            this.InvokeAsync("GenerateCreativityPrompts", new object[] {
                        text}, this.GenerateCreativityPromptsOperationCompleted, userState);
        }
        
        private void OnGenerateCreativityPromptsOperationCompleted(object arg) {
            if ((this.GenerateCreativityPromptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateCreativityPromptsCompleted(this, new GenerateCreativityPromptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerateCreativityClues", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerateCreativityClues(string genericText, string text) {
            object[] results = this.Invoke("GenerateCreativityClues", new object[] {
                        genericText,
                        text});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void GenerateCreativityCluesAsync(string genericText, string text) {
            this.GenerateCreativityCluesAsync(genericText, text, null);
        }
        
        /// CodeRemarks
        public void GenerateCreativityCluesAsync(string genericText, string text, object userState) {
            if ((this.GenerateCreativityCluesOperationCompleted == null)) {
                this.GenerateCreativityCluesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateCreativityCluesOperationCompleted);
            }
            this.InvokeAsync("GenerateCreativityClues", new object[] {
                        genericText,
                        text}, this.GenerateCreativityCluesOperationCompleted, userState);
        }
        
        private void OnGenerateCreativityCluesOperationCompleted(object arg) {
            if ((this.GenerateCreativityCluesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateCreativityCluesCompleted(this, new GenerateCreativityCluesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneratePredicatesFromDocument", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GeneratePredicatesFromDocument(string documentUri, int domainID) {
            this.Invoke("GeneratePredicatesFromDocument", new object[] {
                        documentUri,
                        domainID});
        }
        
        /// CodeRemarks
        public void GeneratePredicatesFromDocumentAsync(string documentUri, int domainID) {
            this.GeneratePredicatesFromDocumentAsync(documentUri, domainID, null);
        }
        
        /// CodeRemarks
        public void GeneratePredicatesFromDocumentAsync(string documentUri, int domainID, object userState) {
            if ((this.GeneratePredicatesFromDocumentOperationCompleted == null)) {
                this.GeneratePredicatesFromDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePredicatesFromDocumentOperationCompleted);
            }
            this.InvokeAsync("GeneratePredicatesFromDocument", new object[] {
                        documentUri,
                        domainID}, this.GeneratePredicatesFromDocumentOperationCompleted, userState);
        }
        
        private void OnGeneratePredicatesFromDocumentOperationCompleted(object arg) {
            if ((this.GeneratePredicatesFromDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePredicatesFromDocumentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneratePredicates", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GeneratePredicates(string name, string assignedID, string author, int domainID, string problem, string solution, string keywords) {
            this.Invoke("GeneratePredicates", new object[] {
                        name,
                        assignedID,
                        author,
                        domainID,
                        problem,
                        solution,
                        keywords});
        }
        
        /// CodeRemarks
        public void GeneratePredicatesAsync(string name, string assignedID, string author, int domainID, string problem, string solution, string keywords) {
            this.GeneratePredicatesAsync(name, assignedID, author, domainID, problem, solution, keywords, null);
        }
        
        /// CodeRemarks
        public void GeneratePredicatesAsync(string name, string assignedID, string author, int domainID, string problem, string solution, string keywords, object userState) {
            if ((this.GeneratePredicatesOperationCompleted == null)) {
                this.GeneratePredicatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneratePredicatesOperationCompleted);
            }
            this.InvokeAsync("GeneratePredicates", new object[] {
                        name,
                        assignedID,
                        author,
                        domainID,
                        problem,
                        solution,
                        keywords}, this.GeneratePredicatesOperationCompleted, userState);
        }
        
        private void OnGeneratePredicatesOperationCompleted(object arg) {
            if ((this.GeneratePredicatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneratePredicatesCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveAllSources", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveAllSources() {
            object[] results = this.Invoke("RetrieveAllSources", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveAllSourcesAsync() {
            this.RetrieveAllSourcesAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveAllSourcesAsync(object userState) {
            if ((this.RetrieveAllSourcesOperationCompleted == null)) {
                this.RetrieveAllSourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveAllSourcesOperationCompleted);
            }
            this.InvokeAsync("RetrieveAllSources", new object[0], this.RetrieveAllSourcesOperationCompleted, userState);
        }
        
        private void OnRetrieveAllSourcesOperationCompleted(object arg) {
            if ((this.RetrieveAllSourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveAllSourcesCompleted(this, new RetrieveAllSourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PerformAntique", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerformAntique(string antiqueRequestXml) {
            object[] results = this.Invoke("PerformAntique", new object[] {
                        antiqueRequestXml});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void PerformAntiqueAsync(string antiqueRequestXml) {
            this.PerformAntiqueAsync(antiqueRequestXml, null);
        }
        
        /// CodeRemarks
        public void PerformAntiqueAsync(string antiqueRequestXml, object userState) {
            if ((this.PerformAntiqueOperationCompleted == null)) {
                this.PerformAntiqueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformAntiqueOperationCompleted);
            }
            this.InvokeAsync("PerformAntique", new object[] {
                        antiqueRequestXml}, this.PerformAntiqueOperationCompleted, userState);
        }
        
        private void OnPerformAntiqueOperationCompleted(object arg) {
            if ((this.PerformAntiqueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformAntiqueCompleted(this, new PerformAntiqueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PerformAntiqueSample", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerformAntiqueSample() {
            object[] results = this.Invoke("PerformAntiqueSample", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void PerformAntiqueSampleAsync() {
            this.PerformAntiqueSampleAsync(null);
        }
        
        /// CodeRemarks
        public void PerformAntiqueSampleAsync(object userState) {
            if ((this.PerformAntiqueSampleOperationCompleted == null)) {
                this.PerformAntiqueSampleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformAntiqueSampleOperationCompleted);
            }
            this.InvokeAsync("PerformAntiqueSample", new object[0], this.PerformAntiqueSampleOperationCompleted, userState);
        }
        
        private void OnPerformAntiqueSampleOperationCompleted(object arg) {
            if ((this.PerformAntiqueSampleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformAntiqueSampleCompleted(this, new PerformAntiqueSampleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void NLParserCompletedEventHandler(object sender, NLParserCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NLParserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NLParserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ValidateRequestXmlCompletedEventHandler(object sender, ValidateRequestXmlCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateRequestXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateRequestXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ValidateRequestXmlUriCompletedEventHandler(object sender, ValidateRequestXmlUriCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateRequestXmlUriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateRequestXmlUriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ValidateXmlCompletedEventHandler(object sender, ValidateXmlCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ValidateXmlUriCompletedEventHandler(object sender, ValidateXmlUriCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateXmlUriCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateXmlUriCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveRequestXmlSchemaCompletedEventHandler(object sender, RetrieveRequestXmlSchemaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveRequestXmlSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveRequestXmlSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveRequestXmlSampleCompletedEventHandler(object sender, RetrieveRequestXmlSampleCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveRequestXmlSampleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveRequestXmlSampleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveResponseXmlSchemaCompletedEventHandler(object sender, RetrieveResponseXmlSchemaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveResponseXmlSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveResponseXmlSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveResponseDetailedXmlSchemaCompletedEventHandler(object sender, RetrieveResponseDetailedXmlSchemaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveResponseDetailedXmlSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveResponseDetailedXmlSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void CalculateSimilarityCompletedEventHandler(object sender, CalculateSimilarityCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateSimilarityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateSimilarityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ConvertToNewDomainCompletedEventHandler(object sender, ConvertToNewDomainCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConvertToNewDomainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConvertToNewDomainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GenerateCreativityPromptsCompletedEventHandler(object sender, GenerateCreativityPromptsCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateCreativityPromptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateCreativityPromptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GenerateCreativityCluesCompletedEventHandler(object sender, GenerateCreativityCluesCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateCreativityCluesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateCreativityCluesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GeneratePredicatesFromDocumentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void GeneratePredicatesCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveAllSourcesCompletedEventHandler(object sender, RetrieveAllSourcesCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveAllSourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveAllSourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void PerformAntiqueCompletedEventHandler(object sender, PerformAntiqueCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformAntiqueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformAntiqueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void PerformAntiqueSampleCompletedEventHandler(object sender, PerformAntiqueSampleCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformAntiqueSampleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformAntiqueSampleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
