// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHunting.eddieService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EDDiE Web ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class EDDiEWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckExistCaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemoveCaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCaseCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveTermsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateRequestXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateResponseXmlOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveRequestXmlSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveResponseXmlSchemaOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveAllSourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveAllSourcesDomainOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformEddieDomainOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformEddieOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformEddieSampleOperationCompleted;
        
        private System.Threading.SendOrPostCallback PerformEddieDomainSampleOperationCompleted;
        
        private System.Threading.SendOrPostCallback StoreXmlDocumentOperationCompleted;
        
        /// CodeRemarks
        public EDDiEWebService() {
            this.Url = "http://achernar.soi.city.ac.uk/ESD/WebServices/EDDiE_WS/EddieService.asmx";
        }
        
        public EDDiEWebService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event CheckExistCaseCompletedEventHandler CheckExistCaseCompleted;
        
        /// CodeRemarks
        public event RemoveCaseCompletedEventHandler RemoveCaseCompleted;
        
        /// CodeRemarks
        public event UpdateCaseCompletedEventHandler UpdateCaseCompleted;
        
        /// CodeRemarks
        public event AddCaseCommentCompletedEventHandler AddCaseCommentCompleted;
        
        /// CodeRemarks
        public event RetrieveTermsCompletedEventHandler RetrieveTermsCompleted;
        
        /// CodeRemarks
        public event ValidateRequestXmlCompletedEventHandler ValidateRequestXmlCompleted;
        
        /// CodeRemarks
        public event ValidateResponseXmlCompletedEventHandler ValidateResponseXmlCompleted;
        
        /// CodeRemarks
        public event RetrieveRequestXmlSchemaCompletedEventHandler RetrieveRequestXmlSchemaCompleted;
        
        /// CodeRemarks
        public event RetrieveResponseXmlSchemaCompletedEventHandler RetrieveResponseXmlSchemaCompleted;
        
        /// CodeRemarks
        public event RetrieveAllSourcesCompletedEventHandler RetrieveAllSourcesCompleted;
        
        /// CodeRemarks
        public event RetrieveAllSourcesDomainCompletedEventHandler RetrieveAllSourcesDomainCompleted;
        
        /// CodeRemarks
        public event PerformEddieDomainCompletedEventHandler PerformEddieDomainCompleted;
        
        /// CodeRemarks
        public event PerformEddieCompletedEventHandler PerformEddieCompleted;
        
        /// CodeRemarks
        public event PerformEddieSampleCompletedEventHandler PerformEddieSampleCompleted;
        
        /// CodeRemarks
        public event PerformEddieDomainSampleCompletedEventHandler PerformEddieDomainSampleCompleted;
        
        /// CodeRemarks
        public event StoreXmlDocumentCompletedEventHandler StoreXmlDocumentCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckExistCase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckExistCase(string facetType, string caseID) {
            object[] results = this.Invoke("CheckExistCase", new object[] {
                        facetType,
                        caseID});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void CheckExistCaseAsync(string facetType, string caseID) {
            this.CheckExistCaseAsync(facetType, caseID, null);
        }
        
        /// CodeRemarks
        public void CheckExistCaseAsync(string facetType, string caseID, object userState) {
            if ((this.CheckExistCaseOperationCompleted == null)) {
                this.CheckExistCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckExistCaseOperationCompleted);
            }
            this.InvokeAsync("CheckExistCase", new object[] {
                        facetType,
                        caseID}, this.CheckExistCaseOperationCompleted, userState);
        }
        
        private void OnCheckExistCaseOperationCompleted(object arg) {
            if ((this.CheckExistCaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckExistCaseCompleted(this, new CheckExistCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RemoveCase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemoveCase(string facetType, string caseID) {
            object[] results = this.Invoke("RemoveCase", new object[] {
                        facetType,
                        caseID});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RemoveCaseAsync(string facetType, string caseID) {
            this.RemoveCaseAsync(facetType, caseID, null);
        }
        
        /// CodeRemarks
        public void RemoveCaseAsync(string facetType, string caseID, object userState) {
            if ((this.RemoveCaseOperationCompleted == null)) {
                this.RemoveCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemoveCaseOperationCompleted);
            }
            this.InvokeAsync("RemoveCase", new object[] {
                        facetType,
                        caseID}, this.RemoveCaseOperationCompleted, userState);
        }
        
        private void OnRemoveCaseOperationCompleted(object arg) {
            if ((this.RemoveCaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemoveCaseCompleted(this, new RemoveCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateCase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateCase(string contentXml, string facetType, string caseID) {
            object[] results = this.Invoke("UpdateCase", new object[] {
                        contentXml,
                        facetType,
                        caseID});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void UpdateCaseAsync(string contentXml, string facetType, string caseID) {
            this.UpdateCaseAsync(contentXml, facetType, caseID, null);
        }
        
        /// CodeRemarks
        public void UpdateCaseAsync(string contentXml, string facetType, string caseID, object userState) {
            if ((this.UpdateCaseOperationCompleted == null)) {
                this.UpdateCaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCaseOperationCompleted);
            }
            this.InvokeAsync("UpdateCase", new object[] {
                        contentXml,
                        facetType,
                        caseID}, this.UpdateCaseOperationCompleted, userState);
        }
        
        private void OnUpdateCaseOperationCompleted(object arg) {
            if ((this.UpdateCaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCaseCompleted(this, new UpdateCaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddCaseComment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddCaseComment(string newCommentText, string caseID) {
            object[] results = this.Invoke("AddCaseComment", new object[] {
                        newCommentText,
                        caseID});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void AddCaseCommentAsync(string newCommentText, string caseID) {
            this.AddCaseCommentAsync(newCommentText, caseID, null);
        }
        
        /// CodeRemarks
        public void AddCaseCommentAsync(string newCommentText, string caseID, object userState) {
            if ((this.AddCaseCommentOperationCompleted == null)) {
                this.AddCaseCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCaseCommentOperationCompleted);
            }
            this.InvokeAsync("AddCaseComment", new object[] {
                        newCommentText,
                        caseID}, this.AddCaseCommentOperationCompleted, userState);
        }
        
        private void OnAddCaseCommentOperationCompleted(object arg) {
            if ((this.AddCaseCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCaseCommentCompleted(this, new AddCaseCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveTerms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveTerms() {
            object[] results = this.Invoke("RetrieveTerms", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveTermsAsync() {
            this.RetrieveTermsAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveTermsAsync(object userState) {
            if ((this.RetrieveTermsOperationCompleted == null)) {
                this.RetrieveTermsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveTermsOperationCompleted);
            }
            this.InvokeAsync("RetrieveTerms", new object[0], this.RetrieveTermsOperationCompleted, userState);
        }
        
        private void OnRetrieveTermsOperationCompleted(object arg) {
            if ((this.RetrieveTermsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveTermsCompleted(this, new RetrieveTermsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateRequestXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateRequestXml(string xml) {
            object[] results = this.Invoke("ValidateRequestXml", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void ValidateRequestXmlAsync(string xml) {
            this.ValidateRequestXmlAsync(xml, null);
        }
        
        /// CodeRemarks
        public void ValidateRequestXmlAsync(string xml, object userState) {
            if ((this.ValidateRequestXmlOperationCompleted == null)) {
                this.ValidateRequestXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateRequestXmlOperationCompleted);
            }
            this.InvokeAsync("ValidateRequestXml", new object[] {
                        xml}, this.ValidateRequestXmlOperationCompleted, userState);
        }
        
        private void OnValidateRequestXmlOperationCompleted(object arg) {
            if ((this.ValidateRequestXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateRequestXmlCompleted(this, new ValidateRequestXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidateResponseXml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ValidateResponseXml(string xml) {
            object[] results = this.Invoke("ValidateResponseXml", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void ValidateResponseXmlAsync(string xml) {
            this.ValidateResponseXmlAsync(xml, null);
        }
        
        /// CodeRemarks
        public void ValidateResponseXmlAsync(string xml, object userState) {
            if ((this.ValidateResponseXmlOperationCompleted == null)) {
                this.ValidateResponseXmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateResponseXmlOperationCompleted);
            }
            this.InvokeAsync("ValidateResponseXml", new object[] {
                        xml}, this.ValidateResponseXmlOperationCompleted, userState);
        }
        
        private void OnValidateResponseXmlOperationCompleted(object arg) {
            if ((this.ValidateResponseXmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateResponseXmlCompleted(this, new ValidateResponseXmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveRequestXmlSchema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveRequestXmlSchema() {
            object[] results = this.Invoke("RetrieveRequestXmlSchema", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveRequestXmlSchemaAsync() {
            this.RetrieveRequestXmlSchemaAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveRequestXmlSchemaAsync(object userState) {
            if ((this.RetrieveRequestXmlSchemaOperationCompleted == null)) {
                this.RetrieveRequestXmlSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveRequestXmlSchemaOperationCompleted);
            }
            this.InvokeAsync("RetrieveRequestXmlSchema", new object[0], this.RetrieveRequestXmlSchemaOperationCompleted, userState);
        }
        
        private void OnRetrieveRequestXmlSchemaOperationCompleted(object arg) {
            if ((this.RetrieveRequestXmlSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveRequestXmlSchemaCompleted(this, new RetrieveRequestXmlSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveResponseXmlSchema", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveResponseXmlSchema() {
            object[] results = this.Invoke("RetrieveResponseXmlSchema", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveResponseXmlSchemaAsync() {
            this.RetrieveResponseXmlSchemaAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveResponseXmlSchemaAsync(object userState) {
            if ((this.RetrieveResponseXmlSchemaOperationCompleted == null)) {
                this.RetrieveResponseXmlSchemaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveResponseXmlSchemaOperationCompleted);
            }
            this.InvokeAsync("RetrieveResponseXmlSchema", new object[0], this.RetrieveResponseXmlSchemaOperationCompleted, userState);
        }
        
        private void OnRetrieveResponseXmlSchemaOperationCompleted(object arg) {
            if ((this.RetrieveResponseXmlSchemaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveResponseXmlSchemaCompleted(this, new RetrieveResponseXmlSchemaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveAllSources", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveAllSources() {
            object[] results = this.Invoke("RetrieveAllSources", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveAllSourcesAsync() {
            this.RetrieveAllSourcesAsync(null);
        }
        
        /// CodeRemarks
        public void RetrieveAllSourcesAsync(object userState) {
            if ((this.RetrieveAllSourcesOperationCompleted == null)) {
                this.RetrieveAllSourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveAllSourcesOperationCompleted);
            }
            this.InvokeAsync("RetrieveAllSources", new object[0], this.RetrieveAllSourcesOperationCompleted, userState);
        }
        
        private void OnRetrieveAllSourcesOperationCompleted(object arg) {
            if ((this.RetrieveAllSourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveAllSourcesCompleted(this, new RetrieveAllSourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RetrieveAllSourcesDomain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RetrieveAllSourcesDomain(string domain) {
            object[] results = this.Invoke("RetrieveAllSourcesDomain", new object[] {
                        domain});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void RetrieveAllSourcesDomainAsync(string domain) {
            this.RetrieveAllSourcesDomainAsync(domain, null);
        }
        
        /// CodeRemarks
        public void RetrieveAllSourcesDomainAsync(string domain, object userState) {
            if ((this.RetrieveAllSourcesDomainOperationCompleted == null)) {
                this.RetrieveAllSourcesDomainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveAllSourcesDomainOperationCompleted);
            }
            this.InvokeAsync("RetrieveAllSourcesDomain", new object[] {
                        domain}, this.RetrieveAllSourcesDomainOperationCompleted, userState);
        }
        
        private void OnRetrieveAllSourcesDomainOperationCompleted(object arg) {
            if ((this.RetrieveAllSourcesDomainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveAllSourcesDomainCompleted(this, new RetrieveAllSourcesDomainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PerformEddieDomain", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerformEddieDomain(string eddieRequestXml, string domain) {
            object[] results = this.Invoke("PerformEddieDomain", new object[] {
                        eddieRequestXml,
                        domain});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void PerformEddieDomainAsync(string eddieRequestXml, string domain) {
            this.PerformEddieDomainAsync(eddieRequestXml, domain, null);
        }
        
        /// CodeRemarks
        public void PerformEddieDomainAsync(string eddieRequestXml, string domain, object userState) {
            if ((this.PerformEddieDomainOperationCompleted == null)) {
                this.PerformEddieDomainOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformEddieDomainOperationCompleted);
            }
            this.InvokeAsync("PerformEddieDomain", new object[] {
                        eddieRequestXml,
                        domain}, this.PerformEddieDomainOperationCompleted, userState);
        }
        
        private void OnPerformEddieDomainOperationCompleted(object arg) {
            if ((this.PerformEddieDomainCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformEddieDomainCompleted(this, new PerformEddieDomainCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PerformEddie", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerformEddie(string eddieRequestXml) {
            object[] results = this.Invoke("PerformEddie", new object[] {
                        eddieRequestXml});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void PerformEddieAsync(string eddieRequestXml) {
            this.PerformEddieAsync(eddieRequestXml, null);
        }
        
        /// CodeRemarks
        public void PerformEddieAsync(string eddieRequestXml, object userState) {
            if ((this.PerformEddieOperationCompleted == null)) {
                this.PerformEddieOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformEddieOperationCompleted);
            }
            this.InvokeAsync("PerformEddie", new object[] {
                        eddieRequestXml}, this.PerformEddieOperationCompleted, userState);
        }
        
        private void OnPerformEddieOperationCompleted(object arg) {
            if ((this.PerformEddieCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformEddieCompleted(this, new PerformEddieCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PerformEddieSample", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerformEddieSample() {
            object[] results = this.Invoke("PerformEddieSample", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void PerformEddieSampleAsync() {
            this.PerformEddieSampleAsync(null);
        }
        
        /// CodeRemarks
        public void PerformEddieSampleAsync(object userState) {
            if ((this.PerformEddieSampleOperationCompleted == null)) {
                this.PerformEddieSampleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformEddieSampleOperationCompleted);
            }
            this.InvokeAsync("PerformEddieSample", new object[0], this.PerformEddieSampleOperationCompleted, userState);
        }
        
        private void OnPerformEddieSampleOperationCompleted(object arg) {
            if ((this.PerformEddieSampleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformEddieSampleCompleted(this, new PerformEddieSampleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PerformEddieDomainSample", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PerformEddieDomainSample(string domain) {
            object[] results = this.Invoke("PerformEddieDomainSample", new object[] {
                        domain});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void PerformEddieDomainSampleAsync(string domain) {
            this.PerformEddieDomainSampleAsync(domain, null);
        }
        
        /// CodeRemarks
        public void PerformEddieDomainSampleAsync(string domain, object userState) {
            if ((this.PerformEddieDomainSampleOperationCompleted == null)) {
                this.PerformEddieDomainSampleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPerformEddieDomainSampleOperationCompleted);
            }
            this.InvokeAsync("PerformEddieDomainSample", new object[] {
                        domain}, this.PerformEddieDomainSampleOperationCompleted, userState);
        }
        
        private void OnPerformEddieDomainSampleOperationCompleted(object arg) {
            if ((this.PerformEddieDomainSampleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PerformEddieDomainSampleCompleted(this, new PerformEddieDomainSampleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StoreXmlDocument", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void StoreXmlDocument(string xmlContent, string facetType, string sourceId) {
            this.Invoke("StoreXmlDocument", new object[] {
                        xmlContent,
                        facetType,
                        sourceId});
        }
        
        /// CodeRemarks
        public void StoreXmlDocumentAsync(string xmlContent, string facetType, string sourceId) {
            this.StoreXmlDocumentAsync(xmlContent, facetType, sourceId, null);
        }
        
        /// CodeRemarks
        public void StoreXmlDocumentAsync(string xmlContent, string facetType, string sourceId, object userState) {
            if ((this.StoreXmlDocumentOperationCompleted == null)) {
                this.StoreXmlDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStoreXmlDocumentOperationCompleted);
            }
            this.InvokeAsync("StoreXmlDocument", new object[] {
                        xmlContent,
                        facetType,
                        sourceId}, this.StoreXmlDocumentOperationCompleted, userState);
        }
        
        private void OnStoreXmlDocumentOperationCompleted(object arg) {
            if ((this.StoreXmlDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StoreXmlDocumentCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void CheckExistCaseCompletedEventHandler(object sender, CheckExistCaseCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckExistCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckExistCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RemoveCaseCompletedEventHandler(object sender, RemoveCaseCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemoveCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemoveCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void UpdateCaseCompletedEventHandler(object sender, UpdateCaseCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void AddCaseCommentCompletedEventHandler(object sender, AddCaseCommentCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddCaseCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddCaseCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveTermsCompletedEventHandler(object sender, RetrieveTermsCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveTermsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveTermsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ValidateRequestXmlCompletedEventHandler(object sender, ValidateRequestXmlCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateRequestXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateRequestXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void ValidateResponseXmlCompletedEventHandler(object sender, ValidateResponseXmlCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateResponseXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateResponseXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveRequestXmlSchemaCompletedEventHandler(object sender, RetrieveRequestXmlSchemaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveRequestXmlSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveRequestXmlSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveResponseXmlSchemaCompletedEventHandler(object sender, RetrieveResponseXmlSchemaCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveResponseXmlSchemaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveResponseXmlSchemaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveAllSourcesCompletedEventHandler(object sender, RetrieveAllSourcesCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveAllSourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveAllSourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void RetrieveAllSourcesDomainCompletedEventHandler(object sender, RetrieveAllSourcesDomainCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveAllSourcesDomainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveAllSourcesDomainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void PerformEddieDomainCompletedEventHandler(object sender, PerformEddieDomainCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformEddieDomainCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformEddieDomainCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void PerformEddieCompletedEventHandler(object sender, PerformEddieCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformEddieCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformEddieCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void PerformEddieSampleCompletedEventHandler(object sender, PerformEddieSampleCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformEddieSampleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformEddieSampleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void PerformEddieDomainSampleCompletedEventHandler(object sender, PerformEddieDomainSampleCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PerformEddieDomainSampleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PerformEddieDomainSampleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    public delegate void StoreXmlDocumentCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
