// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHunting {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
					System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RiskHunting.App_GlobalResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string General_AppName {
            get {
                return ResourceManager.GetString("General.AppName", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_NavigationBar_Title {
            get {
                return ResourceManager.GetString("DescribeRisk.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_NavigationBar_Left {
            get {
                return ResourceManager.GetString("DescribeRisk.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_Author {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Author", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_AuthorFIN {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.AuthorFIN", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_Required {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Required", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_Description {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Description", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_IncidentCatagory {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.IncidentCatagory", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_PersonInvolved {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.PersonInvolved", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_Department {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Department", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_Location {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Location", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_InjuryType {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.InjuryType", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_DateOfIncident {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.DateOfIncident", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Label_UploadPicture {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.UploadPicture", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Button_UploadPicture {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Button.UploadPicture", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Button_CreateIdeas {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Button.CreateIdeas", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Button_ClearForm {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Button.ClearForm", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Button_DeleteRisk {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Button.DeleteRisk", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_NavigationBar_Right {
            get {
                return ResourceManager.GetString("DescribeRisk.NavigationBar.Right", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_IncidentCategory_UnsafeAct {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.IncidentCategory.UnsafeAct", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_IncidentCategory_UnsafeCondition {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.IncidentCategory.UnsafeCondition", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_IncidentCategory_NearMiss {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.IncidentCategory.NearMiss", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_PedestalLine {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.PedestalLine", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_CabLine {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.CabLine", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_AfterPaint {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.AfterPaint", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_PrePaint {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.PrePaint", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_PaintFloor {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.PaintFloor", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_Agv {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.Agv", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_Warehouse {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.Warehouse", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_Maintenance {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.Maintenance", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_RoadTestCentre {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.RoadTestCentre", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_SubAssembly {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.SubAssembly", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_Department_Other {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.Other", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_InjuryType_Abrasions {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Abrasions", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_InjuryType_Burns {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Burns", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_InjuryType_Contusion {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Contusion", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_InjuryType_ForeignBodies {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.ForeignBodies", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_InjuryType_Fractures {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Fractures", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_InjuryType_Hematoma {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Hematoma", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_InjuryType_Sprains {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Sprains", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_InjuryType_None {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.None", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Jan {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Jan", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Feb {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Feb", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Mar {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Mar", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Apr {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Apr", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_May {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.May", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Jun {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Jun", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Jul {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Jul", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Aug {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Aug", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Sep {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Sep", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Oct {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Oct", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Nov {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Nov", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_DropDown_DateOfIncident_Dec {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Dec", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Notification_Empty {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.Empty", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Notification_SuccessSubmit {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.SuccessSubmit", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Notification_FailedSubmit {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.FailedSubmit", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Notification_FailedDelete {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.FailedDelete", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Notification_SuccessDelete {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.SuccessDelete", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Notification_EnterDescription {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.EnterDescription", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Watermark_Author {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Watermark.Author", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Watermark_AuthorFIN {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Watermark.AuthorFIN", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Watermark_Description {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Watermark.Description", resourceCulture);
            }
        }
        
        internal static string DescribeRisk_Form_Watermark_PersonInvolved {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Watermark.PersonInvolved", resourceCulture);
            }
        }
        
        internal static string UploadImage_NavigationBar_Title {
            get {
                return ResourceManager.GetString("UploadImage.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string UploadImage_NavigationBar_Left {
            get {
                return ResourceManager.GetString("UploadImage.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string UploadImage_Button_UploadImage {
            get {
                return ResourceManager.GetString("UploadImage.Button.UploadImage", resourceCulture);
            }
        }
        
        internal static string UploadImage_Form_Button_ChooseFile {
            get {
                return ResourceManager.GetString("UploadImage.Form.Button.ChooseFile", resourceCulture);
            }
        }
        
        internal static string UploadImage_Form_Label_NoFileSelected {
            get {
                return ResourceManager.GetString("UploadImage.Form.Label.NoFileSelected", resourceCulture);
            }
        }
        
        internal static string UploadImage_Notification_SuccessUpload {
            get {
                return ResourceManager.GetString("UploadImage.Notification.SuccessUpload", resourceCulture);
            }
        }
        
        internal static string UploadImage_Form_Label_ImagePreview {
            get {
                return ResourceManager.GetString("UploadImage.Form.Label.ImagePreview", resourceCulture);
            }
        }
        
        internal static string UploadImage_Form_Button_DeleteImage {
            get {
                return ResourceManager.GetString("UploadImage.Form.Button.DeleteImage", resourceCulture);
            }
        }
        
        internal static string UploadImage_Notification_RequiredFields {
            get {
                return ResourceManager.GetString("UploadImage.Notification.RequiredFields", resourceCulture);
            }
        }
        
        internal static string UploadImage_Notification_SelectFile {
            get {
                return ResourceManager.GetString("UploadImage.Notification.SelectFile", resourceCulture);
            }
        }
        
        internal static string UploadImage_Notification_IncorrectFormat {
            get {
                return ResourceManager.GetString("UploadImage.Notification.IncorrectFormat", resourceCulture);
            }
        }
        
        internal static string UploadImage_Notification_FailedUpload {
            get {
                return ResourceManager.GetString("UploadImage.Notification.FailedUpload", resourceCulture);
            }
        }
        
        internal static string UploadImage_Notification_SuccessDelete {
            get {
                return ResourceManager.GetString("UploadImage.Notification.SuccessDelete", resourceCulture);
            }
        }
        
        internal static string UploadImage_Notification_FailedDelete {
            get {
                return ResourceManager.GetString("UploadImage.Notification.FailedDelete", resourceCulture);
            }
        }
        
        internal static string CreateIdeas_NavigationBar_Title {
            get {
                return ResourceManager.GetString("CreateIdeas.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string CreateIdeas_NavigationBar_Left {
            get {
                return ResourceManager.GetString("CreateIdeas.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string CreateIdeas_NavigationBar_Right {
            get {
                return ResourceManager.GetString("CreateIdeas.NavigationBar.Right", resourceCulture);
            }
        }
        
        internal static string CreateIdeas_Form_Button_FindSimilarRisks {
            get {
                return ResourceManager.GetString("CreateIdeas.Form.Button.FindSimilarRisks", resourceCulture);
            }
        }
        
        internal static string CreateIdeas_Form_Button_FindMoreRisks {
            get {
                return ResourceManager.GetString("CreateIdeas.Form.Button.FindMoreRisks", resourceCulture);
            }
        }
        
        internal static string CreateIdeas_Notification_FailedSearch {
            get {
                return ResourceManager.GetString("CreateIdeas.Notification.FailedSearch", resourceCulture);
            }
        }
        
        internal static string CreateIdeas_Notification_NoResults {
            get {
                return ResourceManager.GetString("CreateIdeas.Notification.NoResults", resourceCulture);
            }
        }
        
        internal static string CreateIdeas_Notification_ServiceUnavailable {
            get {
                return ResourceManager.GetString("CreateIdeas.Notification.ServiceUnavailable", resourceCulture);
            }
        }
        
        internal static string PastRisk_NavigationBar_Title {
            get {
                return ResourceManager.GetString("PastRisk.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string PastRisk_NavigationBar_Left {
            get {
                return ResourceManager.GetString("PastRisk.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string PastRisk_Form_Button_NewPrompts {
            get {
                return ResourceManager.GetString("PastRisk.Form.Button.NewPrompts", resourceCulture);
            }
        }
        
        internal static string PastRisk_Form_Label_PreviousResolutions {
            get {
                return ResourceManager.GetString("PastRisk.Form.Label.PreviousResolutions", resourceCulture);
            }
        }
        
        internal static string PastRisk_Form_Label_CreativeGuidance {
            get {
                return ResourceManager.GetString("PastRisk.Form.Label.CreativeGuidance", resourceCulture);
            }
        }
        
        internal static string PastRisk_Notification_SuccessAdd {
            get {
                return ResourceManager.GetString("PastRisk.Notification.SuccessAdd", resourceCulture);
            }
        }
        
        internal static string PastRisk_Notification_FailedGeneratePrompts {
            get {
                return ResourceManager.GetString("PastRisk.Notification.FailedGeneratePrompts", resourceCulture);
            }
        }
        
        internal static string AddIdea_NavigationBar_Title {
            get {
                return ResourceManager.GetString("AddIdea.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string AddIdea_NavigationBar_Left {
            get {
                return ResourceManager.GetString("AddIdea.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string AddIdea_Form_Button_AddIdea {
            get {
                return ResourceManager.GetString("AddIdea.Form.Button.AddIdea", resourceCulture);
            }
        }
        
        internal static string AddIdea_Form_Watermark_EnterIdea {
            get {
                return ResourceManager.GetString("AddIdea.Form.Watermark.EnterIdea", resourceCulture);
            }
        }
        
        internal static string AddIdea_Notification_AddIdea {
            get {
                return ResourceManager.GetString("AddIdea.Notification.AddIdea", resourceCulture);
            }
        }
        
        internal static string EditIdea_NavigationBar_Title {
            get {
                return ResourceManager.GetString("EditIdea.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string EditIdea_NavigationBar_Left {
            get {
                return ResourceManager.GetString("EditIdea.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string EditIdea_Form_Button_UpdateIdea {
            get {
                return ResourceManager.GetString("EditIdea.Form.Button.UpdateIdea", resourceCulture);
            }
        }
        
        internal static string EditIdea_Form_Button_DeleteIdea {
            get {
                return ResourceManager.GetString("EditIdea.Form.Button.DeleteIdea", resourceCulture);
            }
        }
        
        internal static string EditIdea_Form_Watermark_EnterIdea {
            get {
                return ResourceManager.GetString("EditIdea.Form.Watermark.EnterIdea", resourceCulture);
            }
        }
        
        internal static string EditIdea_Notification_AddIdea {
            get {
                return ResourceManager.GetString("EditIdea.Notification.AddIdea", resourceCulture);
            }
        }
        
        internal static string ResolveRisk_NavigationBar_Title {
            get {
                return ResourceManager.GetString("ResolveRisk.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string ResolveRisk_NavigationBar_Left {
            get {
                return ResourceManager.GetString("ResolveRisk.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string ResolveRisk_NavigationBar_Right {
            get {
                return ResourceManager.GetString("ResolveRisk.NavigationBar.Right", resourceCulture);
            }
        }
        
        internal static string ResolveRisk_Form_Button_AddNewIdea {
            get {
                return ResourceManager.GetString("ResolveRisk.Form.Button.AddNewIdea", resourceCulture);
            }
        }
        
        internal static string Summary_NavigationBar_Title {
            get {
                return ResourceManager.GetString("Summary.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string Summary_NavigationBar_Left {
            get {
                return ResourceManager.GetString("Summary.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Label_RiskProblem {
            get {
                return ResourceManager.GetString("Summary.Form.Label.RiskProblem", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Label_ResolutionIdeas {
            get {
                return ResourceManager.GetString("Summary.Form.Label.ResolutionIdeas", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Label_HasItBeenResolved {
            get {
                return ResourceManager.GetString("Summary.Form.Label.HasItBeenResolved", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Label_CaseMarkedAsResolved {
            get {
                return ResourceManager.GetString("Summary.Form.Label.CaseMarkedAsResolved", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_Author {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.Author", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_AuthorFIN {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.AuthorFIN", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_Description {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.Description", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_IncidentCategory {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.IncidentCategory", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_PersonInvolved {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.PersonInvolved", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_Department {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.Department", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_Location {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.Location", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_InjuryType {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.InjuryType", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Table_Label_DateOfIncident {
            get {
                return ResourceManager.GetString("Summary.Form.Table.Label.DateOfIncident", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Button_SeeResolutionIdeas {
            get {
                return ResourceManager.GetString("Summary.Form.Button.SeeResolutionIdeas", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Button_MarkAsResolved {
            get {
                return ResourceManager.GetString("Summary.Form.Button.MarkAsResolved", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Button_SubmitCase {
            get {
                return ResourceManager.GetString("Summary.Form.Button.SubmitCase", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Button_GenerateReport {
            get {
                return ResourceManager.GetString("Summary.Form.Button.GenerateReport", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Button_CreateNewRisk {
            get {
                return ResourceManager.GetString("Summary.Form.Button.CreateNewRisk", resourceCulture);
            }
        }
        
        internal static string Summary_Notification_MarkedAsResolved {
            get {
                return ResourceManager.GetString("Summary.Notification.MarkedAsResolved", resourceCulture);
            }
        }
        
        internal static string Summary_Notification_MarkedAsNotResolved {
            get {
                return ResourceManager.GetString("Summary.Notification.MarkedAsNotResolved", resourceCulture);
            }
        }
        
        internal static string Summary_Form_Label_NoIdeasAvailable {
            get {
                return ResourceManager.GetString("Summary.Form.Label.NoIdeasAvailable", resourceCulture);
            }
        }
        
        internal static string Summary_Notification_FailedUpload {
            get {
                return ResourceManager.GetString("Summary.Notification.FailedUpload", resourceCulture);
            }
        }
        
        internal static string Summary_Email_Label_RiskResolved {
            get {
                return ResourceManager.GetString("Summary.Email.Label.RiskResolved", resourceCulture);
            }
        }
        
        internal static string Summary_Email_Label_ResolvedWithResolutions {
            get {
                return ResourceManager.GetString("Summary.Email.Label.ResolvedWithResolutions", resourceCulture);
            }
        }
        
        internal static string Summary_Email_Label_Recommendations {
            get {
                return ResourceManager.GetString("Summary.Email.Label.Recommendations", resourceCulture);
            }
        }
        
        internal static string MarkCaseAsResolved_NavigationBar_Title {
            get {
                return ResourceManager.GetString("MarkCaseAsResolved.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string MarkCaseAsResolved_NavigationBar_Left {
            get {
                return ResourceManager.GetString("MarkCaseAsResolved.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string MarkCaseAsResolved_Form_Button_SubmitSelection {
            get {
                return ResourceManager.GetString("MarkCaseAsResolved.Form.Button.SubmitSelection", resourceCulture);
            }
        }
        
        internal static string MarkCaseAsResolved_Form_Button_MarkAsNotResolved {
            get {
                return ResourceManager.GetString("MarkCaseAsResolved.Form.Button.MarkAsNotResolved", resourceCulture);
            }
        }
        
        internal static string General_Notification_SomethingWentWrong {
            get {
                return ResourceManager.GetString("General.Notification.SomethingWentWrong", resourceCulture);
            }
        }
        
        internal static string General_Notification_Problems {
            get {
                return ResourceManager.GetString("General.Notification.Problems", resourceCulture);
            }
        }
        
        internal static string General_Notification_ReturnToHome {
            get {
                return ResourceManager.GetString("General.Notification.ReturnToHome", resourceCulture);
            }
        }
        
        internal static string General_Notification_Loading {
            get {
                return ResourceManager.GetString("General.Notification.Loading", resourceCulture);
            }
        }
        
        internal static string ProcessGuidance_CaseResolved_1 {
            get {
                return ResourceManager.GetString("ProcessGuidance.CaseResolved.1", resourceCulture);
            }
        }
        
        internal static string CreativityPrompts_BaseForm {
            get {
                return ResourceManager.GetString("CreativityPrompts.BaseForm", resourceCulture);
            }
        }
        
        internal static string ProcessGuidance_PastRisk_Default {
            get {
                return ResourceManager.GetString("ProcessGuidance.PastRisk.Default", resourceCulture);
            }
        }
        
        internal static string ProcessGuidance_PastRisks_Default {
            get {
                return ResourceManager.GetString("ProcessGuidance.PastRisks.Default", resourceCulture);
            }
        }
        
        internal static string ProcessGuidance_DescribeRisk_Default {
            get {
                return ResourceManager.GetString("ProcessGuidance.DescribeRisk.Default", resourceCulture);
            }
        }
        
        internal static string ProcessGuidance_Summary_Default {
            get {
                return ResourceManager.GetString("ProcessGuidance.Summary.Default", resourceCulture);
            }
        }
        
        internal static string QueryHistory_NavigationBar_Left {
            get {
                return ResourceManager.GetString("QueryHistory.NavigationBar.Left", resourceCulture);
            }
        }
        
        internal static string QueryHistory_NavigationBar_Title {
            get {
                return ResourceManager.GetString("QueryHistory.NavigationBar.Title", resourceCulture);
            }
        }
        
        internal static string QueryHistory_Form_Label_SortBy {
            get {
                return ResourceManager.GetString("QueryHistory.Form.Label.SortBy", resourceCulture);
            }
        }
        
        internal static string QueryHistory_Form_DropDown_Date {
            get {
                return ResourceManager.GetString("QueryHistory.Form.DropDown.Date", resourceCulture);
            }
        }
        
        internal static string QueryHistory_Form_DropDown_Status {
            get {
                return ResourceManager.GetString("QueryHistory.Form.DropDown.Status", resourceCulture);
            }
        }
        
        internal static string QueryHistory_Form_DropDown_Category {
            get {
                return ResourceManager.GetString("QueryHistory.Form.DropDown.Category", resourceCulture);
            }
        }
        
        internal static string QueryHistory_Form_DropDown_Author {
            get {
                return ResourceManager.GetString("QueryHistory.Form.DropDown.Author", resourceCulture);
            }
        }
        
        internal static string QueryHistory_Form_Label_LastModified {
            get {
                return ResourceManager.GetString("QueryHistory.Form.Label.LastModified", resourceCulture);
            }
        }
        
        internal static string QueryHistory_Notification_NoPreviousRisks {
            get {
                return ResourceManager.GetString("QueryHistory.Notification.NoPreviousRisks", resourceCulture);
            }
        }
        
        internal static string PinEntry_Notification_IncorrectPin {
            get {
                return ResourceManager.GetString("PinEntry.Notification.IncorrectPin", resourceCulture);
            }
        }
        
        internal static string Summary_Email_Label_NewRiskSubmittedShort {
            get {
                return ResourceManager.GetString("Summary.Email.Label.NewRiskSubmittedShort", resourceCulture);
            }
        }
        
        internal static string Summary_Email_Label_RiskReportGeneratedShort {
            get {
                return ResourceManager.GetString("Summary.Email.Label.RiskReportGeneratedShort", resourceCulture);
            }
        }
        
        internal static string Summary_Email_Label_NewRiskSubmittedLong {
            get {
                return ResourceManager.GetString("Summary.Email.Label.NewRiskSubmittedLong", resourceCulture);
            }
        }
        
        internal static string Summary_Email_Label_RiskReportGeneratedLong {
            get {
                return ResourceManager.GetString("Summary.Email.Label.RiskReportGeneratedLong", resourceCulture);
            }
        }
    }
}
