// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHunting {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RiskHunting.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string General_AppName {
            get {
                return ResourceManager.GetString("General.AppName", resourceCulture);
            }
        }
        
        public static string DescribeRisk_NavigationBar_Title {
            get {
                return ResourceManager.GetString("DescribeRisk.NavigationBar.Title", resourceCulture);
            }
        }
        
        public static string DescribeRisk_NavigationBar_Left {
            get {
                return ResourceManager.GetString("DescribeRisk.NavigationBar.Left", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_Author {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Author", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_AuthorFIN {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.AuthorFIN", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_Required {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Required", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_Description {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Description", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_IncidentCategory {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.IncidentCategory", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_PersonInvolved {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.PersonInvolved", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_Department {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Department", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_Location {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.Location", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_InjuryType {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.InjuryType", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_DateOfIncident {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.DateOfIncident", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Label_UploadPicture {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Label.UploadPicture", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Button_UploadPicture {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Button.UploadPicture", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Button_CreateIdeas {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Button.CreateIdeas", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Button_ClearForm {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Button.ClearForm", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Button_DeleteRisk {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Button.DeleteRisk", resourceCulture);
            }
        }
        
        public static string DescribeRisk_NavigationBar_Right {
            get {
                return ResourceManager.GetString("DescribeRisk.NavigationBar.Right", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_IncidentCategory_UnsafeAct {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.IncidentCategory.UnsafeAct", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_IncidentCategory_UnsafeCondition {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.IncidentCategory.UnsafeCondition", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_IncidentCategory_NearMiss {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.IncidentCategory.NearMiss", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_PedestalLine {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.PedestalLine", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_CabLine {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.CabLine", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_AfterPaint {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.AfterPaint", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_PrePaint {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.PrePaint", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_PaintFloor {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.PaintFloor", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_Agv {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.Agv", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_Warehouse {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.Warehouse", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_Maintenance {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.Maintenance", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_RoadTestCentre {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.RoadTestCentre", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_SubAssembly {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.SubAssembly", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_Department_Other {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.Department.Other", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_InjuryType_Abrasions {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Abrasions", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_InjuryType_Burns {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Burns", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_InjuryType_Contusion {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Contusion", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_InjuryType_ForeignBodies {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.ForeignBodies", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_InjuryType_Fractures {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Fractures", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_InjuryType_Hematoma {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Hematoma", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_InjuryType_Sprains {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.Sprains", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_InjuryType_None {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.InjuryType.None", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Jan {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Jan", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Feb {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Feb", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Mar {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Mar", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Apr {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Apr", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_May {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.May", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Jun {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Jun", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Jul {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Jul", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Aug {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Aug", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Sep {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Sep", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Oct {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Oct", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Nov {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Nov", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_DropDown_DateOfIncident_Dec {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.DropDown.DateOfIncident.Dec", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Notification_Empty {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.Empty", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Notification_SuccessSubmit {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.SuccessSubmit", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Notification_FailedSubmit {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.FailedSubmit", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Notification_FailedDelete {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.FailedDelete", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Notification_SuccessDelete {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.SuccessDelete", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Notification_EnterDescription {
            get {
                return ResourceManager.GetString("DescribeRisk.Notification.EnterDescription", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Watermark_Author {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Watermark.Author", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Watermark_AuthorFIN {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Watermark.AuthorFIN", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Watermark_Description {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Watermark.Description", resourceCulture);
            }
        }
        
        public static string DescribeRisk_Form_Watermark_PersonInvolved {
            get {
                return ResourceManager.GetString("DescribeRisk.Form.Watermark.PersonInvolved", resourceCulture);
            }
        }
    }
}
