// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHunting {
	
	
	public partial class QueryHistory {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemIdeas;
		
		protected System.Web.UI.WebControls.Label LabelNavigationBarLeft;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl rightbutton;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor onlineStatus;
		
		protected System.Web.UI.HtmlControls.HtmlAnchor offlineStatus;
		
		protected System.Web.UI.WebControls.Label LabelNavigationBarTitle;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl alert_message_notice;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl noticeMessage;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl SortDiv;
		
		protected System.Web.UI.WebControls.Label LabelSortBy;
		
		protected System.Web.UI.WebControls.DropDownList SortDropDown;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl queries;
	}
}
