// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace RiskHunting {
	
	
	public partial class Summary {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSolution;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl TopbarProblemSearchSolution;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl creativeGuidance;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl sourceDiv;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl divIdeas;
		
		protected System.Web.UI.WebControls.Label statusLabel;
		
		protected System.Web.UI.WebControls.Label resolvedCaseLabel;

		protected System.Web.UI.WebControls.Button submit;

		protected System.Web.UI.WebControls.Label LabelHint;

		protected System.Web.UI.WebControls.Button Export;

		protected System.Web.UI.WebControls.Button NewRisk;

		protected System.Web.UI.WebControls.Button Resolved;

		protected System.Web.UI.HtmlControls.HtmlGenericControl alert_message_success;

		protected System.Web.UI.HtmlControls.HtmlGenericControl alert_message_error;

		protected System.Web.UI.HtmlControls.HtmlGenericControl successMessage;

		protected System.Web.UI.HtmlControls.HtmlGenericControl errorMessage;
	
		protected System.Web.UI.WebControls.Label LabelNavigationBarLeft;

		protected System.Web.UI.WebControls.Label LabelNavigationBarTitle;

		protected System.Web.UI.WebControls.Label LabelRiskProblem;

		protected System.Web.UI.WebControls.Label LabelResolutionIdeas;

	
	}
}
